title: Login Lesson
description: Frontend for Login/Signup Lesson
owner_name: Finn C, Justin N, Theo H
github_username: F1nnC
github_repo: "Login-Lesson"
baseurl: "/Login-Lesson/"
remote_theme: jekyll/minima
minima:
plugins:
- jekyll-remote-theme
future: true
